### ISSUE TITLE
rubycas-server is breaking the ActiveSupport 4.0 build

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/aker#29]
The version of `rubycas-server` that Aker uses for its integration tests can no longer be run using ActiveRecord 4.0 (which, in turn, needs ActiveSupport 4.0).  We get this:

```
  undefined method `set_table_name' for #<Class:0x007fa27d86bce0> (NoMethodError)
gems/ruby-1.9.3-p448/gems/activerecord-4.0.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
gems/ruby-1.9.3-p448/bundler/gems/rubycas-server-cedf6cd676e3/lib/casserver/model.rb:56:in `<class:LoginTicket>'
gems/ruby-1.9.3-p448/bundler/gems/rubycas-server-cedf6cd676e3/lib/casserver/model.rb:55:in `<module:Model>'
gems/ruby-1.9.3-p448/bundler/gems/rubycas-server-cedf6cd676e3/lib/casserver/model.rb:4:in `<top (required)>'
```

Two solutions:
1. Use something that isn't RubyCAS-Server.
2. Fix RubyCAS-Server to work with ActiveRecord 4.0.  (We have our own fork.)

**Comment by hannahwhy** [comment]
> 1. Use something that isn't RubyCAS-Server.

#30 is one possibility.  Using Jasig CAS (i.e. via `castanet-testing`) is another.
